### ISSUE TITLE
Allow multiple callbacks for a given command

### ISSUE THREAD

**Issue by daurnimator** [mirrexagon/lua-irc-engine#13]
Many modules might want to know e.g. when PRIVMSG occurs.

I suggest allowing multiple callbacks per-event (but still only one "handler").

**Comment by mirrexagon** [comment]
You mean modules that add commands (ie. `base`, `channel`, `message`)? In that case, you should be able to use hooks, which I haven't documented properly, but are mentioned here: https://github.com/mirrexagon/lua-irc-engine#modules-and-the-standard-modules
They're called with the same arguments as handlers.

**Comment by daurnimator** [comment]
Ah I didn't understand what hooks were.

The only thing I guess is this TODO:

> TODO: Hooks should probably be called with handler_return if the handler returned something, like callbacks.
