### ISSUE TITLE
Hooks fired with no arguments

### ISSUE THREAD

**Issue by daurnimator** [mirrexagon/lua-irc-engine#15]
e.g. my PRIVMSG hook still gets fired on a CTCP; however with no arguments because the 'handler' returned nothing.

I think the fix is to not call callbacks/hooks if the handler returns nothing?

**Comment by mirrexagon** [comment]
Ah yeah, sounds right, thanks.

**Comment by daurnimator** [comment]
@mirrexagon thanks for quick merge and release!

**Comment by mirrexagon** [comment]
@daurnimator No problem!
