### ISSUE TITLE
Why did you delete `nixpkgs-esp-dev`?

### ISSUE THREAD

**Issue by taktoa** [mirrexagon/lua-irc-engine#18]
Completely unrelated to this repository, but I noticed your `nixpkgs-esp-dev` overlay repository via the Google cache. Do you still have the source code? Why did you remove it from GitHub?

**Comment by mirrexagon** [comment]
I have a bad habit of removing old stuff I don't use anymore (or haven't used in a while) and I think is not that great. I still have it, I'll restore the repo.

**Comment by mirrexagon** [comment]
https://github.com/mirrexagon/nixpkgs-esp-dev
